Update ChannelTabs.plugin.js - Fix not showing server icons
samfundev/BetterDiscordStuff pull request #17
Opened 2024-10-09 22:40 UTC by Vampical

Fix not showing server icons for https://github.com/samfundev/BetterDiscordStuff/issues/16

2024-10-12 23:09 UTC, angsaysroar approved these changes

2024-10-12 23:16 UTC, angsaysroar requested changes
I downloaded this and the issue with the server icon not updating is still persistent in this version.

This was after I deleted ALL files I had for ChannelTabs from my plugins forward and downloading this file and placing it in the plugins folder.

2024-10-22 08:06 UTC, Vampical commented
> I downloaded this and the issue with the server icon not updating is still persistent in this version.
> 
> This was after I deleted ALL files I had for ChannelTabs from my plugins forward and downloading this file and placing it in the plugins folder.

Because you deleted a file like ChannelTabs new_78693360 xxxxxxxxxxxx.config.json, and you also downloaded a version without a patch, in fact, everything works for me considering that I have about 30 plugins and nothing conflicts (and it can't)

You need to reopen the tab for it to update the icon.

2024-12-07 04:35 UTC, samfundev commented
This works great, thanks for the contribution! Merging...

2024-12-07 04:36 UTC, merged